---
- name: Adjust configurations based on time
  hosts: ubuntu-01
  become: true
  gather_facts: false
  vars_files:
    - files/vault.yaml
  
  tasks:
    - name: Run nginx role
      include_role:
        name: nginx_config
    - name: Run rsyslog role
      include_role:
        name: rsyslog_config